Modulo 03/09 - Codificação para Back-End/SiteFinal/sitefinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.core.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Modulo 03/09 - Codificação para Back-End/SiteFinal/apps/core/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()
    foto = models.ImageField(upload_to="foto_perfil")

    def __str__(self):
        return self.nome
    
class Empresa(models.Model):
    razao_social = models.CharField(max_length=100)
    cnpj = models.PositiveIntegerField()

    def __str__(self):
        return self.razao_social

class Categoria(models.Model):
    tipo = models.CharField(max_length=100)

    def __str__(self):
        return self.tipo

class Servico(models.Model):
    tipo_servico = models.CharField(max_length=100)
    valor_servico = models.DecimalField(decimal_places=2, max_digits=10)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.tipo_servico

class OrdemServico(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    servico = models.ManyToManyField(Servico)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "OS: " + self.id + " | " + self.cliente.nome
    
class Produto(models.Model):
    nome_produto = models.CharField(max_length=100)
    valor_produto = models.DecimalField(decimal_places=2, max_digits=10)
    descricao = models.TextField()

    def __str__(self):
        return self.nome_produto
    

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   
    </head>
    <body>
        {% block titulo %}{% endblock %}
        {% block conteudo %} {% endblock %}
    </body>
</html>

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/conf-excluir.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Confirmar exclusão</title>
    </head>
    <body>
        <h2>Confirmar exclusão</h2>

        <p>Você confirma a exclusão de: {{ valor }} ?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit">Confirmar</button>
            <a href="#" onclick="window.history.back()">
                <button type="button">Cancelar</button>
            </a>
        </form>
    </body>
</html>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/form-categoria.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
    
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "pg_criar_empresa" %}">Empresa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link  active" href="{% url "pg_criar_categoria" %}">Categoria</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_criar_servico" %}">Voltar</a>
        </li>
    </ul>
    
{% endblock %}
{% block conteudo %}
<h2>Formulário Categoria</h2>
    <div class="form">
      <form method="post" id="form_categoria">
          {% csrf_token %}
          <p>
              <label for="id_tipo">Tipo:</label>
              <input type="text" class="border" name="tipo" maxlength="100" required="" id="id_tipo" value="{{categoria.tipo}}">
          </p>
          <button type="submit" class="btn btn-primary">Salvar</button>
          <a href="{% url "pg_criar_categoria" %}">
              <button type="button"  class="btn btn-danger">Cancelar</button>
          </a>
      </form>
    </div>
    <h2>Lista de Categorias</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tipo</th>
                <th scope="col"=>Opções</th>
            </tr>
        </thead>      
        <tbody>
            {% for categoria in categorias %}
                <tr>
                    <th scope="row">{{categoria.id}}</th>
                    <td>{{ categoria.tipo }}</td>
                    <td>
                         <div class="btns_formulario">
                            <a href="{% url "pg_editar_categoria" categoria.id %}">
                                <img src="https://img.icons8.com/?size=100&id=AuMLFRmG95tQ&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="editar"> 
                                
                            </a>
                            <a href="{% url "pg_excluir_categoria" categoria.id %}">
                                <img src="https://img.icons8.com/?size=100&id=67432&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="excluir">
                                
                                
                            </a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/form-cliente.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
  
  <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url "pg_criar_cliente" %}">Cliente</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "pg_criar_empresa" %}">Empresa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
      </li>
  </ul>
{% endblock %}
{% block conteudo %}   

    <h2>Formulário Cliente</h2>

    <form method="POST" id="form-cliente">
        {% csrf_token %}
        <p>
          <label for="id_cliente">Nome</label>
          <input type="text" name="nome" maxlength="100" id="nome" value="{{cliente.nome}}">
        </p>

        <p>
          <label for="id_cliente">Data de Nascimento</label>
          <input type="date" name="data_nascimento" maxlength="100" id="data_nascimento" value="{{cliente.data_nascimento}}">
        </p>

        <p>
          <label for="id_cliente">Foto</label>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="foto">
            <p>
              <button type="submit" class="btn btn-primary">Salvar</button>
              <a href="{% url "pg_criar_cliente" %}">
                <button type="button" class="btn btn-danger">Cancelar</button>
              </a>
            </p>
          </form>
        </p>
    </form>

    <h2>Lista de Clientes</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Cliente</th>
          <th scope="col">Data de Nascimento</th>
          <th scope="col">Foto</th>
        </tr>
      </thead>
      <tbody>
        {% for cliente in clientes %}
          <tr>
            <th scope="row">{{cliente.id}}</th>
            <td>{{cliente.nome}}</td>
            <td>{{cliente.data_nascimento}}</td>
            <td>{{cliente.foto}}</td>

            <td>
              <div class="btns_formulario">
                <a href="{% url "pg_editar_cliente" cliente.id %}">
                  <img src="https://img.icons8.com/?size=100&id=AuMLFRmG95tQ&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="editar cliente">
                </a>
                <a href="{% url "pg_excluir_cliente" cliente.id %}">
                  <img src="https://img.icons8.com/?size=100&id=67432&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="excluir cliente">
                </a>
            </div>
            </td>

          </tr>
        {% endfor %}
      </tbody>
    </table> 
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/form-empresa.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
    
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url "pg_criar_empresa" %}">Empresa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
        </li>
    </ul>
{% endblock %}
{% block conteudo %}
    <h2>Formulário Empresa</h2>
    <div class="form">
      <form method="post" id="form-empresa">
          {% csrf_token %}
          <p>
            <label for="id_empresa">Razão social:</label>
            <input type="text" class="border" name="razao_social" maxlength="100" required="" id="razao_social" value="{{empresa.razao_social}}">
          </p>
          <p>
            <label for="id_cnpj">CNPJ:</label>
            <input type="text" class="border" name="cnpj" maxlength="100" required="" id="cnpj" value="{{empresa.cnpj}}">
          </p>
          <button type="submit" class="btn btn-primary">Salvar</button>
          <a href="{% url "pg_criar_empresa" %}">
              <button type="button" class="btn btn-danger">Cancelar</button>
          </a>
      </form>
    </div>
    <h2>Lista de Empresas</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Razão Social</th>
          <th scope="col">CNPJ</th>
          <th scope="col">Opções</th>
        </tr>
      </thead>
      <tbody>
        {% for empresa in empresas %}
          <tr>
            <th scope="row">{{empresa.id}}</th>
            <td>{{empresa.razao_social}}</td>
            <td>{{empresa.cnpj}}</td>
            <td>
              <div class="btns_formulario">
                <a href="{% url "pg_editar_empresa" empresa.id %}">
                  <img src="https://img.icons8.com/?size=100&id=AuMLFRmG95tQ&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="editar empresa">
                </a>
                <a href="{% url "pg_excluir_empresa" empresa.id %}">
                  <img src="https://img.icons8.com/?size=100&id=67432&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="excluir empresa">
                </a>
            </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/form-ordemservico.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}
  
  <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "pg_criar_empresa" %}">Empresa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
      </li>
  </ul>
{% endblock %}
{% block conteudo %}

  <h2>Formulário Ordem de Serviço</h2>

  <form method="POST" id= "form-ordemservico">
      {% csrf_token %}
      <p>
          <label for="cliente">Cliente</label>
          <select name="cliente_id" id="cliente_id">{{ ordemservico.cliente.nome}}
            <option value="{{ ordemservico.cliente_id }}" selected="{{ordemservico.cliente_id}}">{{ ordemservico.cliente.nome}}</option>
            {% for cliente in clientes %}
              <option value="{{ cliente_id }}">{{ cliente.nome }}</option>
            {% endfor %}
          </select>
      </p>

      <p>
        <label for="servico">Serviço</label>
        <select name="servico_id" id="servico_id">
          <option value="{{ ordemservico.servico_id }}" selected="{{ordemservico.servico_id}}">{{ ordemservico.servico.tipo}}</option>
          {% for servico in servicos %}
            <option value="{{ servico.id }}">{{ servico.tipo }}</option>
          {% endfor %}
        </select>
      </p>

      <p>
        <label for="data">Data do serviço:</label>
        <input type="date" name="data" id="data" value="{{ ordemservico.data }}">
      </p>
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="{% url "pg_criar_ordemservico" %}">
          <button type="button" class="btn btn-danger">Cancelar</button>
      </a>
  </form>

  <h2>Liste de ordem de serviços</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Cliente</th>
        <th scope="col">Serviço</th>
        <th scope="col">Data</th>
        <th scope="col">Opçôes</th>
      </tr>
    </thead>
      <tbody>
        {% for ordemservico in ordemservicos %}
          <tr>
            <th scope="row">{{ordemservico.id}}</th>
            <td>{{ordemservico.cliente.nome}}</td>
            <td>{{ordemservico.servico.tipo}}</td>
            <td>{{ordemservico.data}}</td>
            <td>
              <div class="btns_formulario">
                <a href="{% url "pg_editar_ordemservico" ordemservico.id %}">
                    <img src="https://img.icons8.com/?size=100&id=AuMLFRmG95tQ&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="editar"> 
                    
                </a>
                <a href="{% url "pg_excluir_ordemservico" ordemservico.id %}">
                    <img src="https://img.icons8.com/?size=100&id=67432&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="excluir">
                    
                    
                </a>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
  </table>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/form-produto.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}

<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_empresa" %}">Empresa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link  active " href="{% url "pg_criar_produto" %}">Produto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
    </li>
</ul>
{% endblock %}
{% block conteudo %}
  <h2>Formulário Produto</h2>
  <div class="form">
    <form method="POST" id="form_produto">
      {% csrf_token %}
      <p>
        <label for="id_produto">Nome:</label>
        <input type="text" name="nome" maxlength="100" id="nome" value="{{produto.nome}}">
      </p>
      <p>
        <label for="id_produto">Valor:</label>
        <input type="number" name="valor" maxlength="100" id="valor" value="produto.valor">
      </p>
      <p>
        <label for="id_produto">Descrição:</label>
        <input type="text" name="descricao" maxlength="1000" id="descricao" value="{{produto.descricao}}">
      </p>
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="{% url "pg_criar_produto" %}">
          <button type="button" class="btn btn-danger">Cancelar</button>
      </a>
    </form>
  </div>

  <h2>Lista de Produtos</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Valor</th>
        <th scope="col">Descrição</th>
        <th scope="col">Opções</th>
      </tr>
    </thead>
    <tbody>
      {% for produto in produtos %}
        <tr>
          <th scope="row">{{produto.id}}</th>
          <td>{{produto.nome}}</td>
          <td>{{produto.valor}}</td>
          <td>{{produto.descricao}}</td>
          <td>
            <div class="btns_formulario">
              <a href="{% url "pg_editar_produto" produto.id %}">
                <img src="https://img.icons8.com/?size=100&id=AuMLFRmG95tQ&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="editar produto">
              </a>
              <a href="{% url "pg_excluir_produto" produto.id %}">
                <img src="https://img.icons8.com/?size=100&id=67432&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="excluir produto">
              </a>
          </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/form-servico.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}

<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_empresa" %}">Empresa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active " href="{% url "pg_criar_servico" %}">Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
    </li>
</ul>
{% endblock %}
{% block conteudo %}

  <h2>Formulário Serviço</h2>
  <div class="form">
    <form method="post">
      {% csrf_token %}
      <p>
        <label for="tipo">Tipo serviço:</label>
        <input type="text" name="tipo" maxlength="100" required="" id="tipo" value="{{servico.tipo}}">
      </p>
          
      <p>
        <label for="valor">Valor serviço:</label>
        <input type="number" name="valor" step="0.01" required="" id="valor" value="{{servico.valor}}">
      </p>
           
      <p>
      <label for="id_empresa">Empresa:</label>
      <select name="empresa_id" id="empresa_id">
          <option value="servico.empresa.id" selected="{{servico.empresa.id}}">{{servico.empresa.razao_social}}</option>
          {% for empresa in empresas %}
              <option value="{{ empresa.id }}">{{ empresa.razao_social }}</option>
          {% endfor %}
      </select>
      </p>
       
      <p>
      <label for="id_categoria">Categoria:</label>
      <select name="categoria_id" id="categoria_id">
          <option value="{{servico.categoria.id}}" selected="servico.categoria.id">{{servico.categoria.tipo}}</option>
          {% for categoria in categorias %}
              <option value="{{ categoria.id }}">{{ categoria.tipo }}</option>
          {% endfor %}
      </select>
      </p>
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="{% url "pg_inicial" %}">
          <button type="button" class="btn btn-danger">Cancelar</button>
      </a>
    </form>
  </div>   

  <h2>Lista de Serviços</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Tipo</th>
        <th scope="col">Valor</th>
        <th scope="col">Empresa</th>
        <th scope="col">Categoria</th>
        <th scope="col">Opções</th>
      </tr>
    </thead>
    <tbody>
      {% for servico in servicos %}
        <tr>
          <th scope="row">{{servico.id}}</th>
          <td>{{servico.tipo}}</td>
          <td>{{servico.valor}}</td>
          <td>{{servico.empresa.razao_social}}</td>
          <td>{{servico.categoria.tipo}}</td>
          <td>
            <div class="btns_formulario">
              <a href="{% url "pg_editar_servico" servico.id %}">
                <img src="https://img.icons8.com/?size=100&id=AuMLFRmG95tQ&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="editar serviço">
              </a>
              <a href="{% url "pg_excluir_servico" servico.id %}">
                <img src="https://img.icons8.com/?size=100&id=67432&format=png&color=000000" heght="20" width="30" data-bs-toggle="tooltip" title="excluir serviço">
              </a>
          </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/ibge.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}

<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_empresa" %}">Empresa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active " href="{% url "ibge" %}">IBGE</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
    </li>
</ul>
{% endblock %}
{% block conteudo %}
  <section class="container">
      <nav>
          <ul class="nav">
              <li class="nav-item">Municipios do Piaui-IBGE</li>
          </ul>
      </nav>
  </section>
  <div class="container">
      <table class="table">
          <thead class="thead-dark">
              <tr>
                  <th scope="col">ID</th>
                  <th scope="col">MUNICIPIO</th>
                  <th scope="col">MICROREGIÃO</th>
                  <th scope="col">MESOREGIÃO</th>
              </tr>
          </thead>
          <tbody>
              {% for municipio in municipios %}
                  <tr>
                      <th scope="row">{{municipio.id}}</th>
                      <td>{{municipio.nome}}</td>
                      <td>{{municipio.microregiao.nome}}</td>
                      <td>{{municipio.microregiao.mesoregiao.nome}}</td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
{% endblock %}

Modulo 03/09 - Codificação para Back-End/SiteFinal/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block titulo %}

<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_ordemservico" %}">Ordem de Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "pg_criar_cliente" %}">Cliente</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url "pg_criar_empresa" %}">Empresa</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_servico" %}">Serviço</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_produto" %}">Produto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_criar_categoria" %}">Categoria</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "ibge" %}">IBGE</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url "pg_inicial" %}">Voltar</a>
    </li>
</ul>
{% endblock %}
{% block conteudo %}
        
{% for os in ordemservicos %}
    <div class="card">
        <div class="rotulo-card">
            <span>{{ os.cliente.nome }}</span>
            <span>{{ os.data_servico }}</span>
        </div>
        
        <ul>
            {% for servico in os.servico.all %}
                <li>{{ servico.tipo_servico }} - R$ {{ servico.valor_servico }} - {{ servico.empresa }}</li>
            {% endfor %}
        </ul>
        
        <span class="valor-total">R$ {{ os.valor_total }}</span>
        <a class="valor-total" href="{% url "pg_excluir_ordemservico" os.id %}">
            <span>Excluir OS</span>
        </a>
    </div>
{% endfor %}
{% endblock %}